### ISSUE TITLE
Adatbázis hozzáadása

### ISSUE THREAD

**Issue by paroczigergo** [bme-temalabor-instagram/egyesrepo#6]
Kérdés: milyen adatbázist használjunk? MySQL-re gondoltam (mert azt ismerem :D ), de lehet más is.
Elsősorban a képek adatainak kéne valami jó struktúrát kitalálni.

**Comment by OMMHOA** [comment]
felőlem teljesen jó a MySQL. eddig még nem használtam, szóval szívesen kipróbálnám.

**Comment by paroczigergo** [comment]
okés, akkor majd hétfőn kitaláljuk a sémát hozzá.

**Comment by OMMHOA** [comment]
rendben
